version: "3.7"
services:
  rp-tengine:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile_tengine
    volumes:
      - nginx-storage:/usr/local/nginx
      - nginx-log:/var/log/nginx
    ports:
      - 80:80
      - 443:443

  nginx-exporter:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile_nginx_exporter
    volumes:
      - nginx-log:/var/log/nginx
      - ./nginx_log_exporter.yml:/etc/prometheus-nginxlog-exporter.yml
    depends_on:
      - rp-tengine
    ports:
      - 4040:4040

  json-exporter:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile_json_exp
    volumes:
      - nginx-storage:/usr/local/nginx
    links:
      - rp-tengine
    depends_on:
      - rp-tengine

  prometheus:
    restart: always
    volumes:
      - prometheus-dir:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - nginx-exporter
      - rp-tengine
    ports:
      - 9090:9090
    image: prom/prometheus
    depends_on:
      - rp-tengine
      - nginx-exporter
      - json-exporter

volumes:
  nginx-storage:
  nginx-log:
  prometheus-dir:
