global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    scrape_interval: 15s
    static_configs:
      - targets: ['nginx-exporter:4040']

  - job_name: 'vts'
    scrape_interval: 15s
    static_configs:
      - targets: ['my_nginx:80']

